name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: ./Challenge-LIS/dotnet restore
        working-directory: Challenge-LIS
      - name: Build
        run: ./Challenge-LIS/dotnet build --configuration Release --no-restore
        working-directory: Challenge-LIS
      - name: Test
        run: ./Challenge-LIS/dotnet test --no-restore --verbosity normal
        working-directory: Challenge-LIS
